import type {
  UserProfile,
  WhisperMatch,
  TrialPartnership,
  ChatMessage,
  EventChatMessage,
  ScheduleSession,
  AppNotification,
  Stamp,
} from '../types';

const PEXELS = 'https://images.pexels.com/photos';

export const CURRENT_USER: UserProfile = {
  id: 'u0',
  name: 'Abeba Girma',
  discipline: 'UI/UX Designer',
  bio: 'Addis-based designer obsessed with building tools that unlock African creativity. Former lead at Qene Studios. Now going independent.',
  location: 'Addis Ababa, ET',
  avatarUrl: '/images/avatars/abeba.png',
  currentIntent: 'Seeking a developer co-founder for my creative tools startup',
  portfolioLinks: [
    { label: 'Portfolio', url: '#', icon: 'website' },
    { label: 'Dribbble', url: '#', icon: 'dribbble' },
    { label: 'LinkedIn', url: '#', icon: 'linkedin' },
  ],
  stamps: [
    {
      id: 's1',
      type: 'attendance',
      label: 'CRAFT Addis 2025',
      description: 'Attended CRAFT Addis Festival 2025',
      eventName: 'CRAFT Addis 2025',
      issuedAt: '2025-03-02',
      color: '#F26419',
    },
    {
      id: 's2',
      type: 'speaker',
      label: 'Speaker',
      description: 'Delivered a talk at CRAFT Addis 2025',
      eventName: 'CRAFT Addis 2025',
      issuedAt: '2025-03-01',
      color: '#F5A623',
    },
    {
      id: 's3',
      type: 'partnership',
      label: 'Connector',
      description: 'Initiated 5+ trial partnerships',
      eventName: 'CRAFT Addis 2025',
      issuedAt: '2025-03-02',
      color: '#0ABFBC',
    },
  ],
  isLocal: true,
  isOnline: true,
  doNotDisturb: false,
  joinedAt: '2025-01-10',
};

export const PARTICIPANTS: UserProfile[] = [
  {
    id: 'u1',
    name: 'Koffi Mensah',
    discipline: 'Digital Artist',
    bio: 'Lagos-based digital artist merging Afrofuturism with generative systems. Featured in Artsy & Christie\'s NFT auction.',
    location: 'Lagos, NG',
    avatarUrl: '/images/avatars/koffi.png',
    currentIntent: 'Looking for UI designer to co-build a generative art platform',
    portfolioLinks: [{ label: 'Instagram', url: '#', icon: 'instagram' }],
    stamps: [],
    isLocal: false,
    isOnline: true,
    doNotDisturb: false,
    joinedAt: '2025-02-01',
  },
  {
    id: 'u2',
    name: 'Priya Sharma',
    discipline: 'Brand Strategist',
    bio: 'Nairobi creative strategist helping African brands find their global voice. 10+ years in pan-African brand building.',
    location: 'Nairobi, KE',
    avatarUrl: '/images/avatars/priya.png',
    currentIntent: 'Seeking designers & storytellers for a pan-African brand collective',
    portfolioLinks: [{ label: 'LinkedIn', url: '#', icon: 'linkedin' }],
    stamps: [],
    isLocal: false,
    isOnline: true,
    doNotDisturb: false,
    joinedAt: '2025-02-05',
  },
  {
    id: 'u3',
    name: 'Yonas Tesfaye',
    discipline: 'Filmmaker',
    bio: 'Award-winning filmmaker from Addis. Documenting the creative renaissance happening across East Africa.',
    location: 'Addis Ababa, ET',
    avatarUrl: '/images/avatars/yonas.png',
    currentIntent: 'Looking for UI/UX partner to build an indie filmmaker distribution app',
    portfolioLinks: [{ label: 'YouTube', url: '#', icon: 'youtube' }],
    stamps: [],
    isLocal: true,
    isOnline: true,
    doNotDisturb: false,
    joinedAt: '2025-02-08',
  },
  {
    id: 'u4',
    name: 'Amara Diallo',
    discipline: 'Fashion Designer',
    bio: 'Dakar-based fashion innovator blending traditional West African textiles with modern silhouettes. LVMH Prize nominee.',
    location: 'Dakar, SN',
    avatarUrl: '/images/avatars/amara.png',
    currentIntent: 'Seeking a creative technologist to build an AR try-on experience',
    portfolioLinks: [{ label: 'Instagram', url: '#', icon: 'instagram' }],
    stamps: [],
    isLocal: false,
    isOnline: false,
    doNotDisturb: false,
    joinedAt: '2025-02-10',
  },
  {
    id: 'u5',
    name: 'Marcus Chen',
    discipline: 'Creative Technologist',
    bio: 'Cape Town-based creative coder building immersive experiences at the intersection of art and emerging technology.',
    location: 'Cape Town, ZA',
    avatarUrl: '/images/avatars/marcus.png',
    currentIntent: 'Offering AR/WebGL expertise, looking for creative directors to collaborate',
    portfolioLinks: [{ label: 'GitHub', url: '#', icon: 'github' }],
    stamps: [],
    isLocal: false,
    isOnline: true,
    doNotDisturb: false,
    joinedAt: '2025-01-22',
  },
  {
    id: 'u6',
    name: 'Fatima Al-Hassan',
    discipline: 'Graphic Designer',
    bio: 'Cairo-based visual designer crafting bold identities for North African creatives and cultural institutions.',
    location: 'Cairo, EG',
    avatarUrl: '/images/avatars/abeba.png',
    currentIntent: 'Open to design commissions & looking for music producers to collaborate',
    portfolioLinks: [{ label: 'Behance', url: '#', icon: 'behance' }],
    stamps: [],
    isLocal: false,
    isOnline: true,
    doNotDisturb: true,
    joinedAt: '2025-02-12',
  },
  {
    id: 'u7',
    name: 'Emmanuel Osei',
    discipline: 'Music Producer',
    bio: 'Accra-based producer blending Highlife, Afrobeats, and electronic production. Published on Spotify, Apple Music, Tidal.',
    location: 'Accra, GH',
    avatarUrl: '/images/avatars/koffi.png',
    currentIntent: 'Seeking visual artists and designers for an audio-visual EP project',
    portfolioLinks: [{ label: 'Instagram', url: '#', icon: 'instagram' }],
    stamps: [],
    isLocal: false,
    isOnline: true,
    doNotDisturb: false,
    joinedAt: '2025-02-03',
  },
  {
    id: 'u8',
    name: 'Sofia Andrade',
    discipline: 'UX Researcher',
    bio: 'Johannesburg-based researcher uncovering what makes digital products work for African audiences. Open to research partnerships.',
    location: 'Johannesburg, ZA',
    avatarUrl: '/images/avatars/priya.png',
    currentIntent: 'Looking for product teams building for African markets to partner on research',
    portfolioLinks: [{ label: 'LinkedIn', url: '#', icon: 'linkedin' }],
    stamps: [],
    isLocal: false,
    isOnline: false,
    doNotDisturb: false,
    joinedAt: '2025-02-15',
  },
  {
    id: 'u9',
    name: 'Tariq Ibrahim',
    discipline: 'Product Manager',
    bio: 'Addis-based PM building fintech products for Ethiopia\'s growing digital economy. Previously at Telebirr & Safaricom.',
    location: 'Addis Ababa, ET',
    avatarUrl: '/images/avatars/yonas.png',
    currentIntent: 'Seeking a UX designer for a mobile payment product launching in Q3',
    portfolioLinks: [{ label: 'LinkedIn', url: '#', icon: 'linkedin' }],
    stamps: [],
    isLocal: true,
    isOnline: true,
    doNotDisturb: false,
    joinedAt: '2025-01-30',
  },
  {
    id: 'u10',
    name: 'Léa Dubois',
    discipline: 'Creative Director',
    bio: 'Creative director shaping visual narratives for global African brands. Based in Lagos, working globally.',
    location: 'Lagos, NG',
    avatarUrl: '/images/avatars/amara.png',
    currentIntent: 'Building a roster of African designers for international brand campaigns',
    portfolioLinks: [{ label: 'Instagram', url: '#', icon: 'instagram' }],
    stamps: [],
    isLocal: false,
    isOnline: true,
    doNotDisturb: false,
    joinedAt: '2025-02-01',
  },
  {
    id: 'u11',
    name: 'Kwame Asante',
    discipline: 'Game Developer',
    bio: 'Indie game developer in Accra building Africa\'s first AAA mobile gaming studio. Unity & Unreal certified.',
    location: 'Accra, GH',
    avatarUrl: '/images/avatars/marcus.png',
    currentIntent: 'Looking for character artists and sound designers to join the studio',
    portfolioLinks: [{ label: 'GitHub', url: '#', icon: 'github' }],
    stamps: [],
    isLocal: false,
    isOnline: false,
    doNotDisturb: false,
    joinedAt: '2025-02-18',
  },
];

export const WHISPER_MATCHES: WhisperMatch[] = [
  {
    id: 'm1',
    user: PARTICIPANTS[0],
    matchScore: 94,
    myIntent: 'Seeking a developer co-founder for my creative tools startup',
    theirIntent: 'Looking for UI designer to co-build a generative art platform',
    matchedKeywords: ['designer', 'co-build', 'creative'],
    status: 'new',
    createdAt: '2026-02-18T08:32:00Z',
  },
  {
    id: 'm2',
    user: PARTICIPANTS[8],
    matchScore: 88,
    myIntent: 'Seeking a developer co-founder for my creative tools startup',
    theirIntent: 'Seeking a UX designer for a mobile payment product launching in Q3',
    matchedKeywords: ['UX', 'designer', 'startup'],
    status: 'new',
    createdAt: '2026-02-18T09:10:00Z',
  },
  {
    id: 'm3',
    user: PARTICIPANTS[2],
    matchScore: 81,
    myIntent: 'Seeking a developer co-founder for my creative tools startup',
    theirIntent: 'Looking for UI/UX partner to build an indie filmmaker distribution app',
    matchedKeywords: ['UI/UX', 'build', 'app'],
    status: 'viewed',
    createdAt: '2026-02-18T07:55:00Z',
  },
  {
    id: 'm4',
    user: PARTICIPANTS[9],
    matchScore: 77,
    myIntent: 'Seeking a developer co-founder for my creative tools startup',
    theirIntent: 'Building a roster of African designers for international brand campaigns',
    matchedKeywords: ['designer', 'African', 'creative'],
    status: 'new',
    createdAt: '2026-02-18T10:15:00Z',
  },
  {
    id: 'm5',
    user: PARTICIPANTS[6],
    matchScore: 71,
    myIntent: 'Seeking a developer co-founder for my creative tools startup',
    theirIntent: 'Seeking visual artists and designers for an audio-visual EP project',
    matchedKeywords: ['designer', 'creative'],
    status: 'viewed',
    createdAt: '2026-02-17T18:40:00Z',
  },
  {
    id: 'm6',
    user: PARTICIPANTS[1],
    matchScore: 65,
    myIntent: 'Seeking a developer co-founder for my creative tools startup',
    theirIntent: 'Seeking designers & storytellers for a pan-African brand collective',
    matchedKeywords: ['designers', 'creative'],
    status: 'new',
    createdAt: '2026-02-18T11:00:00Z',
  },
  {
    id: 'm7',
    user: PARTICIPANTS[4],
    matchScore: 60,
    myIntent: 'Seeking a developer co-founder for my creative tools startup',
    theirIntent: 'Offering AR/WebGL expertise, looking for creative directors to collaborate',
    matchedKeywords: ['creative', 'collaborate'],
    status: 'viewed',
    createdAt: '2026-02-17T16:20:00Z',
  },
];

export const PARTNERSHIPS: TrialPartnership[] = [
  {
    id: 'p1',
    partner: PARTICIPANTS[0],
    status: 'active',
    myIntent: 'Seeking a developer co-founder for my creative tools startup',
    partnerIntent: 'Looking for UI designer to co-build a generative art platform',
    lastMessage: 'I love the direction you\'re thinking. Want to set up a call this week?',
    lastMessageAt: '2026-02-18T10:45:00Z',
    unreadCount: 2,
    createdAt: '2026-02-17T14:20:00Z',
  },
  {
    id: 'p2',
    partner: PARTICIPANTS[2],
    status: 'active',
    myIntent: 'Seeking a developer co-founder for my creative tools startup',
    partnerIntent: 'Looking for UI/UX partner to build an indie filmmaker distribution app',
    lastMessage: 'The wireframes look incredible. Can we start a prototype sprint?',
    lastMessageAt: '2026-02-18T08:30:00Z',
    unreadCount: 0,
    createdAt: '2026-02-16T11:00:00Z',
  },
  {
    id: 'p3',
    partner: PARTICIPANTS[6],
    status: 'active',
    myIntent: 'Seeking a developer co-founder for my creative tools startup',
    partnerIntent: 'Seeking visual artists and designers for an audio-visual EP project',
    lastMessage: 'Sent you the moodboard for the visual identity.',
    lastMessageAt: '2026-02-17T20:15:00Z',
    unreadCount: 1,
    createdAt: '2026-02-15T09:30:00Z',
  },
];

export const CHAT_MESSAGES: Record<string, ChatMessage[]> = {
  p1: [
    { id: 'c1', senderId: 'u1', text: 'Hey Abeba! Saw your intent on the Whisper Feed — this feels like a real match. I\'ve been wanting a co-builder for the generative platform.', sentAt: '2026-02-17T14:22:00Z', isOwn: false },
    { id: 'c2', senderId: 'u0', text: 'Koffi! I was thinking the same. Your work on Artsy is exactly the energy I want to bring into a platform product.', sentAt: '2026-02-17T14:28:00Z', isOwn: true },
    { id: 'c3', senderId: 'u1', text: 'I\'ve been thinking about a platform where creators can build generative art NFTs without writing code. A visual-first approach.', sentAt: '2026-02-17T14:35:00Z', isOwn: false },
    { id: 'c4', senderId: 'u0', text: 'That\'s my exact thesis! I\'ve been sketching flows for something similar. I can share the Figma file — it\'s early but the direction is solid.', sentAt: '2026-02-17T14:40:00Z', isOwn: true },
    { id: 'c5', senderId: 'u1', text: 'Yes please! And I can share some technical POCs I\'ve been building in p5.js. Let\'s see if the visions align.', sentAt: '2026-02-17T14:45:00Z', isOwn: false },
    { id: 'c6', senderId: 'u0', text: 'Sent you the Figma link. Particularly proud of the canvas editor section.', sentAt: '2026-02-18T09:00:00Z', isOwn: true },
    { id: 'c7', senderId: 'u1', text: 'This is STUNNING. The intent layer UI is exactly what I had in mind but couldn\'t design. We need to build this.', sentAt: '2026-02-18T10:30:00Z', isOwn: false },
    { id: 'c8', senderId: 'u1', text: 'I love the direction you\'re thinking. Want to set up a call this week?', sentAt: '2026-02-18T10:45:00Z', isOwn: false },
  ],
  p2: [
    { id: 'c1', senderId: 'u3', text: 'Abeba, caught your profile on the Whisper Feed. I\'m building a platform for indie filmmakers to distribute work without going through the big gatekeepers.', sentAt: '2026-02-16T11:02:00Z', isOwn: false },
    { id: 'c2', senderId: 'u0', text: 'Yonas! I\'ve been following your documentary series — the Lalibela one was incredible. This sounds exactly like the kind of problem worth solving.', sentAt: '2026-02-16T11:15:00Z', isOwn: true },
    { id: 'c3', senderId: 'u3', text: 'Thank you! I need someone who understands both the creative side and the product side. The user journey for a filmmaker is so different from a mainstream consumer app.', sentAt: '2026-02-16T11:30:00Z', isOwn: false },
    { id: 'c4', senderId: 'u0', text: 'Totally agree. I\'ve been thinking about creator-first product design a lot. Let me put together some initial wireframes based on what you\'ve described.', sentAt: '2026-02-16T12:00:00Z', isOwn: true },
    { id: 'c5', senderId: 'u3', text: 'That would be amazing. I\'ll send you the product brief I\'ve been working on.', sentAt: '2026-02-16T12:10:00Z', isOwn: false },
    { id: 'c6', senderId: 'u0', text: 'Got the brief — this is more thought-out than most funded startup decks I\'ve seen. Give me 2 days on the wireframes.', sentAt: '2026-02-17T09:00:00Z', isOwn: true },
    { id: 'c7', senderId: 'u3', text: 'The wireframes look incredible. Can we start a prototype sprint?', sentAt: '2026-02-18T08:30:00Z', isOwn: false },
  ],
  p3: [
    { id: 'c1', senderId: 'u7', text: 'Abeba, Emmanuel here from Accra. I\'m producing an audio-visual EP and need a designer who can build a visual identity that lives both in print and in motion.', sentAt: '2026-02-15T09:32:00Z', isOwn: false },
    { id: 'c2', senderId: 'u0', text: 'Emmanuel! I\'ve been listening to your SoundCloud. The textural approach to production is so visual already — I can totally see a direction.', sentAt: '2026-02-15T10:00:00Z', isOwn: true },
    { id: 'c3', senderId: 'u7', text: 'Exactly what I wanted to hear. I\'m thinking deep blues, earth tones, and patterns drawn from kente weaving — but made abstract and modern.', sentAt: '2026-02-15T10:20:00Z', isOwn: false },
    { id: 'c4', senderId: 'u0', text: 'I\'m already sketching. The kente-abstraction direction is fresh — let me explore that with a digital textile language.', sentAt: '2026-02-15T11:00:00Z', isOwn: true },
    { id: 'c5', senderId: 'u7', text: 'Sent you the moodboard for the visual identity.', sentAt: '2026-02-17T20:15:00Z', isOwn: false },
  ],
};

export const SCHEDULE: ScheduleSession[] = [
  {
    id: 'ss1', day: 1, startTime: '09:00', endTime: '09:45',
    title: 'Opening Ceremony: The African Creative Renaissance',
    description: 'A bold opening exploring how Africa\'s creative class is reshaping global culture, technology, and industry on its own terms.',
    type: 'Keynote', stage: 'Main Stage', isHappeningNow: false, isBookmarked: true,
    speakers: [
      { name: 'Amira Bekele', discipline: 'Festival Director', avatarUrl: '/images/avatars/abeba.png' },
    ],
  },
  {
    id: 'ss2', day: 1, startTime: '10:00', endTime: '11:00',
    title: 'Design as Infrastructure: Building Africa\'s Visual Language',
    description: 'Panelists from across the continent discuss how intentional design thinking is becoming a tool for economic and cultural sovereignty.',
    type: 'Panel', stage: 'Main Stage', isHappeningNow: false, isBookmarked: false,
    speakers: [
      { name: 'Abeba Girma', discipline: 'UI/UX Designer', avatarUrl: '/images/avatars/abeba.png' },
      { name: 'Léa Dubois', discipline: 'Creative Director', avatarUrl: '/images/avatars/amara.png' },
      { name: 'Fatima Al-Hassan', discipline: 'Graphic Designer', avatarUrl: '/images/avatars/priya.png' },
    ],
  },
  {
    id: 'ss3', day: 1, startTime: '11:30', endTime: '13:00',
    title: 'Generative Futures: AI & African Creativity',
    description: 'Hands-on lab exploring how African artists are using and subverting AI tools to generate work rooted in local aesthetics.',
    type: 'Lab', stage: 'Lab', isHappeningNow: true, isBookmarked: true,
    speakers: [
      { name: 'Koffi Mensah', discipline: 'Digital Artist', avatarUrl: '/images/avatars/koffi.png' },
      { name: 'Marcus Chen', discipline: 'Creative Technologist', avatarUrl: '/images/avatars/marcus.png' },
    ],
  },
  {
    id: 'ss4', day: 1, startTime: '14:00', endTime: '15:00',
    title: 'Soundscapes of the Continent: Music as Cultural Export',
    description: 'A fireside conversation on how African music producers are building global audiences without losing cultural authenticity.',
    type: 'Panel', stage: 'Cafe Stage', isHappeningNow: false, isBookmarked: false,
    speakers: [
      { name: 'Emmanuel Osei', discipline: 'Music Producer', avatarUrl: '/images/avatars/yonas.png' },
    ],
  },
  {
    id: 'ss5', day: 1, startTime: '15:30', endTime: '16:30',
    title: 'Fashion Forward: Textiles, Identity & Global Markets',
    description: 'West and East African fashion designers discuss scaling without diluting the cultural codes embedded in their work.',
    type: 'Panel', stage: 'Gallery', isHappeningNow: false, isBookmarked: false,
    speakers: [
      { name: 'Amara Diallo', discipline: 'Fashion Designer', avatarUrl: '/images/avatars/amara.png' },
    ],
  },
  {
    id: 'ss6', day: 1, startTime: '17:00', endTime: '18:00',
    title: 'Networking: Creative Discovery Hour',
    description: 'Structured open networking powered by CRAFT Connect Whisper Matching. Bring your best intent.',
    type: 'Networking', stage: 'Courtyard', isHappeningNow: false, isBookmarked: true,
    speakers: [],
  },
  {
    id: 'ss7', day: 2, startTime: '09:30', endTime: '10:30',
    title: 'Film Beyond Borders: Indie Distribution in the Streaming Age',
    description: 'Filmmakers and distribution execs tackle how African indie film can break through in a Netflix-dominated world.',
    type: 'Panel', stage: 'Main Stage', isHappeningNow: false, isBookmarked: false,
    speakers: [
      { name: 'Yonas Tesfaye', discipline: 'Filmmaker', avatarUrl: '/images/avatars/yonas.png' },
    ],
  },
  {
    id: 'ss8', day: 2, startTime: '11:00', endTime: '12:30',
    title: 'UX for Africa: Designing Products That Actually Work Here',
    description: 'A deep workshop on low-bandwidth UX, feature phone considerations, and building for the 1 billion.',
    type: 'Workshop', stage: 'Studio A', isHappeningNow: false, isBookmarked: true,
    speakers: [
      { name: 'Sofia Andrade', discipline: 'UX Researcher', avatarUrl: '/images/avatars/priya.png' },
      { name: 'Abeba Girma', discipline: 'UI/UX Designer', avatarUrl: '/images/avatars/abeba.png' },
    ],
  },
  {
    id: 'ss9', day: 2, startTime: '14:00', endTime: '15:00',
    title: 'Gaming in Africa: The Next Frontier',
    description: 'How African game studios are building IP, finding audiences, and rewriting the rules of the global gaming industry.',
    type: 'Panel', stage: 'Main Stage', isHappeningNow: false, isBookmarked: false,
    speakers: [
      { name: 'Kwame Asante', discipline: 'Game Developer', avatarUrl: '/images/avatars/marcus.png' },
    ],
  },
  {
    id: 'ss10', day: 2, startTime: '15:30', endTime: '17:00',
    title: 'Brand Identity Workshop: Crafting the African Mark',
    description: 'An intensive workshop walking through the process of building a brand identity that is culturally specific and globally resonant.',
    type: 'Workshop', stage: 'Studio A', isHappeningNow: false, isBookmarked: false,
    speakers: [
      { name: 'Priya Sharma', discipline: 'Brand Strategist', avatarUrl: '/images/avatars/priya.png' },
    ],
  },
  {
    id: 'ss11', day: 3, startTime: '10:00', endTime: '11:30',
    title: 'The Creative Economy: Turning Practice into Livelihood',
    description: 'A frank conversation on monetization, funding, and building sustainable creative businesses across the continent.',
    type: 'Panel', stage: 'Main Stage', isHappeningNow: false, isBookmarked: false,
    speakers: [
      { name: 'Tariq Ibrahim', discipline: 'Product Manager', avatarUrl: '/images/avatars/yonas.png' },
    ],
  },
  {
    id: 'ss12', day: 3, startTime: '13:00', endTime: '14:00',
    title: 'Live Performance: Afrofuturism in Sound',
    description: 'A live performance blending electronic production, traditional instrumentation, and live visuals.',
    type: 'Performance', stage: 'Main Stage', isHappeningNow: false, isBookmarked: true,
    speakers: [
      { name: 'Emmanuel Osei', discipline: 'Music Producer', avatarUrl: '/images/avatars/koffi.png' },
    ],
  },
  {
    id: 'ss13', day: 3, startTime: '15:00', endTime: '16:00',
    title: 'Closing Keynote: Building Tomorrow\'s Creative Infrastructure',
    description: 'A visionary close to CRAFT Addis 2026 charting what the next year of the creative economy could look like.',
    type: 'Keynote', stage: 'Main Stage', isHappeningNow: false, isBookmarked: false,
    speakers: [
      { name: 'Amira Bekele', discipline: 'Festival Director', avatarUrl: '/images/avatars/abeba.png' },
    ],
  },
];

export const EVENT_CHAT: EventChatMessage[] = [
  { id: 'ec1', sender: { id: 'u3', name: 'Yonas T.', discipline: 'Filmmaker', avatarUrl: '/images/avatars/yonas.png', isLocal: true }, text: 'The opening ceremony just gave me chills. This is the energy.', sentAt: '09:52' },
  { id: 'ec2', sender: { id: 'u2', name: 'Priya S.', discipline: 'Brand Strategist', avatarUrl: '/images/avatars/priya.png', isLocal: false }, text: 'Watching from Nairobi — the stream quality is exceptional this year!', sentAt: '09:53' },
  { id: 'ec3', sender: { id: 'u5', name: 'Marcus C.', discipline: 'Creative Technologist', avatarUrl: '/images/avatars/marcus.png', isLocal: false }, text: 'That slide about African visual language being infrastructure — that\'s the most articulate framing I\'ve heard.', sentAt: '09:58' },
  { id: 'ec4', sender: { id: 'u7', name: 'Emmanuel O.', discipline: 'Music Producer', avatarUrl: '/images/avatars/koffi.png', isLocal: false }, text: 'Connecting from Accra. Really wish I was in the room for this panel.', sentAt: '10:02' },
  { id: 'ec5', sender: { id: 'u1', name: 'Koffi M.', discipline: 'Digital Artist', avatarUrl: '/images/avatars/koffi.png', isLocal: false }, text: 'Can someone share the specific frameworks they mentioned for the "visual sovereignty" approach?', sentAt: '10:07' },
  { id: 'ec6', sender: { id: 'u6', name: 'Fatima A.', discipline: 'Graphic Designer', avatarUrl: '/images/avatars/abeba.png', isLocal: false }, text: 'The slide deck will be available after the session per the moderator announcement.', sentAt: '10:09' },
  { id: 'ec7', sender: { id: 'u4', name: 'Amara D.', discipline: 'Fashion Designer', avatarUrl: '/images/avatars/amara.png', isLocal: false }, text: 'Love this panel but I want a whole separate session on fashion as infrastructure. What Amara said resonates deeply.', sentAt: '10:12' },
  { id: 'ec8', sender: { id: 'u9', name: 'Tariq I.', discipline: 'Product Manager', avatarUrl: '/images/avatars/yonas.png', isLocal: true }, text: 'Question for the panel: how do we ensure that the digital tools we build actually serve local creators first, rather than being optimized for Western investors?', sentAt: '10:15' },
  { id: 'ec9', sender: { id: 'u8', name: 'Sofia A.', discipline: 'UX Researcher', avatarUrl: '/images/avatars/priya.png', isLocal: false }, text: 'Tariq that\'s exactly what my research has been exploring. Come find me after the session — or let\'s connect on the Whisper Feed!', sentAt: '10:17' },
  { id: 'ec10', sender: { id: 'u0', name: 'Abeba G.', discipline: 'UI/UX Designer', avatarUrl: '/images/avatars/abeba.png', isLocal: true }, text: 'This is the conversation that should be happening everywhere. Thrilled to be on this panel today 🙏', sentAt: '10:20', isOwn: true },
];

export const NOTIFICATIONS: AppNotification[] = [
  { id: 'n1', type: 'match', title: 'New Whisper Match', body: 'Koffi Mensah (Digital Artist, Lagos) matches your intent with 94% alignment.', isRead: false, createdAt: '2026-02-18T08:32:00Z', referenceId: 'm1' },
  { id: 'n2', type: 'message', title: 'New message from Koffi M.', body: 'I love the direction you\'re thinking. Want to set up a call this week?', isRead: false, createdAt: '2026-02-18T10:45:00Z', referenceId: 'p1' },
  { id: 'n3', type: 'match', title: 'New Whisper Match', body: 'Tariq Ibrahim (Product Manager, Addis) is seeking a UX designer — strong match.', isRead: false, createdAt: '2026-02-18T09:10:00Z', referenceId: 'm2' },
  { id: 'n4', type: 'schedule', title: 'Session starting soon', body: '"Generative Futures: AI & African Creativity" begins in 15 minutes at the Lab.', isRead: true, createdAt: '2026-02-18T11:15:00Z', referenceId: 'ss3' },
  { id: 'n5', type: 'message', title: 'New message from Yonas T.', body: 'The wireframes look incredible. Can we start a prototype sprint?', isRead: true, createdAt: '2026-02-18T08:30:00Z', referenceId: 'p2' },
  { id: 'n6', type: 'stamp', title: 'Stamp Earned: Early Adopter', body: 'You were among the first 100 to activate your Digital Passport at CRAFT Addis 2026.', isRead: true, createdAt: '2026-02-18T07:00:00Z' },
  { id: 'n7', type: 'match', title: 'New Whisper Match', body: 'Léa Dubois (Creative Director, Lagos) is building a roster of African designers.', isRead: true, createdAt: '2026-02-18T10:15:00Z', referenceId: 'm4' },
  { id: 'n8', type: 'system', title: 'Welcome to CRAFT Connect', body: 'Your Digital Passport is live. Set your intent to start receiving Whisper matches.', isRead: true, createdAt: '2026-02-18T06:55:00Z' },
  { id: 'n9', type: 'schedule', title: 'Design as Infrastructure — starting now', body: 'The panel is live on the Main Stage. You\'re speaking in 10 minutes!', isRead: true, createdAt: '2026-02-18T09:50:00Z', referenceId: 'ss2' },
  { id: 'n10', type: 'message', title: 'New message from Emmanuel O.', body: 'Sent you the moodboard for the visual identity.', isRead: true, createdAt: '2026-02-17T20:15:00Z', referenceId: 'p3' },
];

export const DISCIPLINES = [
  'All', 'UI/UX Designer', 'Filmmaker', 'Digital Artist', 'Fashion Designer',
  'Brand Strategist', 'Music Producer', 'Game Developer', 'Creative Technologist',
  'UX Researcher', 'Product Manager', 'Graphic Designer', 'Creative Director',
] as const;
